### PR TITLE
Refactor where appropriate

### PR DESCRIPTION
**Pull request by 0xmichalis**
Check for errors immediately after an error has been returned from a
function call, add error checking after ReadAll calls, and move
json.Unmarshal calls into their following if statements (more idiomatic)

### CODE REVIEW

**Comment by cpg** [comment]
As you can see in the build logs, nil cannot be returned as a string: https://travis-ci.org/amahi/go-themoviedb/jobs/34308357

Can you fix those and we merge?

**Comment by 0xmichalis** [comment]
Yup, fixed.

**Comment by cpg** [comment]
I'm curious how did you find the library and if you would like to share how you are using it. Perhaps we can make a list of uses of the library at the end of the readme.

**Comment by 0xmichalis** [comment]
I am not actively using it, i just stumbled across it while skimming through the Amahi repositories.

**Pull request merged**
